Micronaut MCP Server support is based on the https://github.com/modelcontextprotocol/java-sdk[MCP Java SDK].

You need to use the following dependency:

dependency:micronaut-mcp-server[groupId=io.micronaut.mcp]

WARNING: The MCP Java SDK is coupled to Jackson Databind. Thus, you will need to use https://docs.micronaut.io/latest/guide/#serializationUsingJacksonDatabind[Micronaut Jackson Databind] instead of https://micronaut-projects.github.io/micronaut-serialization/latest/guide/[Micronaut Serialization].

== Server Type

To create a server, you will need to define the property `micronaut.mcp.server.type`
with one of the values `SYNC`, `ASYNC`, `STATELESS_SYNC`, `STATELESS_ASYNC`.

The async types allow you to define primitives (tools, prompts or resources) with call handlers wrapped in a Project Reactor `Mono`.

For https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#stdio[stdio transport], choose either `SYNC` or `ASYNC`.

For https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#streamable-http[HTTP transport], choose either `STATELESS_SYNC` or `STATELESS_ASYNC`.

Then, to create primitives (tools, prompts or resources), you will create beans of a particular type (typically in a https://docs.micronaut.io/latest/guide/#factories[bean factory]).
The bean type depends on the server type selected:

|===
| `micronaut.mcp.server.type` | Transport | Prompt Bean Type | Tool Bean Type | Resource Bean Type | Resource Template Bean Type

|SYNC
|stdio
|`McpServerFeatures.SyncPromptSpecification`
|`McpServerFeatures.SyncToolSpecification`
|`McpServerFeatures.SyncResourceSpecification`
|`McpSchema.ResourceTemplate`

|ASYNC
|stdio
|`McpServerFeatures.AsyncPromptSpecification`
|`McpServerFeatures.AsyncToolSpecification`
|`McpServerFeatures.AsyncResourceSpecification`
|`McpSchema.ResourceTemplate`

|STATELESS_SYNC
|http
|`McpStatelessServerFeatures.SyncPromptSpecification`
|`McpStatelessServerFeatures.SyncToolSpecification`
|`McpServerFeatures.SyncResourceSpecification`
|`McpSchema.ResourceTemplate`

|STATELESS_ASYNC
|http
|`McpStatelessServerFeatures.AsyncPromptSpecification`
|`McpStatelessServerFeatures.AsyncToolSpecification`
|`McpStatelessServerFeatures.AsyncResourceSpecification`
|`McpSchema.ResourceTemplate`
|===

== STDIO Transport Sample configuration
For stdio transport, your configuration may look like

[configuration]
----
micronaut:
  mcp:
    server:
      type: SYNC
      info:
        name: 'pgn-resources'
        version: '1.0.0'
----

== HTTP Transport Sample configuration

[configuration]
----
micronaut:
  mcp:
    server:
      type: STATELESS_SYNC
      info:
        name: 'pgn-resources'
        version: '1.0.0'
----




In addition, you can create beans of type https://docs.micronaut.io/latest/guide/#events[`BeanCreatedEventListener`] to listener to builders:

- `McpSchema.ServerCapabilities.Builder`
