micronaut.application.name=World Chess Championship 2024 PGN
micronaut.mcp.server.info.name=world-chess-championship-2024-pgn
micronaut.mcp.server.info.version=0.0.1
micronaut.mcp.server.type=STATELESS_SYNC
